services:
  - type: web
    name: laravel-ecommerce-hd2406
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeploy: true
    healthCheckPath: /up
    envVars:
      - key: APP_NAME
        value: UrbanCart
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        sync: false
      - key: APP_URL
        sync: false
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: info
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/html/database/database.sqlite
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: sync
      - key: FILESYSTEM_DISK
        value: public
      - key: MAIL_MAILER
        value: log
      - key: MAIL_FROM_ADDRESS
        sync: false
      - key: MAIL_FROM_NAME
        value: UrbanCart
      - key: SEED_ADMIN_EMAIL
        sync: false
      - key: SEED_ADMIN_PASSWORD
        sync: false
